In [1]:
# Exercise 1 : Array Creation and Manipulation
# Instructions
# Create a 1D NumPy array containing numbers from 0 to 9.

# Expected Output:



# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np

array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
# Exercise 2 : Type Conversion and Array Operations
# Instructions
# Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

# Expected Output:



# array([3, 2, 0, 1, 2])
float_list = [3.14, 2.17, 0, 1, 2]
array_int = np.array(float_list, dtype=int)
print(array_int)

[3 2 0 1 2]


In [3]:
# Exercise 3 : Working with Multi-Dimensional Arrays
# Instructions
# Create a 3x3 NumPy array with values ranging from 1 to 9.

# Expected Output:



# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])
array_3x3 = np.arange(1, 10).reshape(3, 3)
print(array_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
# Instructions
# Create a 2D NumPy array of shape (4, 5) filled with random numbers.

# Expected Output:



# array([[0.56, 0.85, 0.01, 0.42, 0.68],
#        [0.22, 0.37, 0.73, 0.93, 0.39],
#        [0.44, 0.03, 0.87, 0.02, 0.83],
#        [0.78, 0.87, 0.98, 0.80, 0.46]])
import numpy as np

arr = np.random.random((4, 5))
print(np.round(arr, 2))


[[0.6  0.46 0.8  0.39 0.31]
 [0.33 0.89 0.51 0.22 0.59]
 [0.26 0.88 0.88 0.74 0.32]
 [0.64 0.69 0.91 0.99 0.68]]


In [6]:
# Exercise 5 : Indexing Arrays
# Instructions
# Select the second row from a given 2D NumPy array.

# Expected Output:



# array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

array = np.array([[21, 22, 23, 22, 22], [20, 21, 22, 23, 24], [21, 22, 23, 22, 22]])
second_row = array[1]
print(second_row)


[20 21 22 23 24]


In [7]:
# Exercise 6 : Reversing elements
# Instructions
# Reverse the order of elements in a given 1D NumPy array (first element becomes last).

# Expected Output:



# array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

array_1d = np.arange(10)
reversed_array = array_1d[::-1]
print(reversed_array)


[9 8 7 6 5 4 3 2 1 0]


In [8]:
# Exercise 7 : Identity Matrix
# Instructions
# Create a 4x4 identity matrix using NumPy.

# Expected Output:



# array([[1., 0., 0., 0.],
#        [0., 1., 0., 0.],
#        [0., 0., 1., 0.],
#        [0., 0., 0., 1.]])

identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# Exercise 8 : Simple Aggregate Funcs
# Instructions
# Find the sum and average of a given 1D array.

# Expected Output:



# Sum: 45, Average: 4.5

array_1d = np.arange(10)
sum_array = np.sum(array_1d)
average_array = np.mean(array_1d)
print(f"Sum: {sum_array}, Average: {average_array}")


Sum: 45, Average: 4.5


In [10]:
# Exercise 9 : Create Array and Change its Structure
# Instructions
# Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

# Expected Output:



# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20]])

array_1d = np.arange(1, 21)
reshaped_array = array_1d.reshape(4, 5)
print(reshaped_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [11]:
# Exercise 10 : Conditional Selection of Values
# Instructions
# Extract all odd numbers from a given NumPy array.

# Expected Output:



# array([1, 3, 5, 7, 9])

array_1d = np.arange(10)
odd_numbers = array_1d[array_1d % 2 == 1]
print(odd_numbers)



[1 3 5 7 9]
